/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/learning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Summary
         * @description How much manager feedback there is, and how much of it can train the model.
         */
        get: operations["summary_api_v1_admin_learning_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/learning/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export
         * @description Training examples as JSON Lines, for `train_student.py --feedback` on Kaggle.
         */
        get: operations["export_api_v1_admin_learning_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Decisions */
        get: operations["list_decisions_api_v1_decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decisions/{key}/thresholds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thresholds */
        get: operations["get_thresholds_api_v1_decisions__key__thresholds_get"];
        /**
         * Update Thresholds
         * @description New cut-offs become a new version (audited); the next run uses them.
         */
        put: operations["update_thresholds_api_v1_decisions__key__thresholds_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eval/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reports */
        get: operations["list_reports_api_v1_eval_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/eval/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_v1_eval_reports__report_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/match-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All Runs */
        get: operations["all_runs_api_v1_match_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/match-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_match_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/match-runs/{run_id}/excluded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Excluded */
        get: operations["excluded_api_v1_match_runs__run_id__excluded_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/match-runs/{run_id}/shortlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Shortlist */
        get: operations["shortlist_api_v1_match_runs__run_id__shortlist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shortlist-items/{item_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Feedback */
        put: operations["save_feedback_api_v1_shortlist_items__item_id__feedback_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Skills */
        get: operations["list_skills_api_v1_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_v1_tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_api_v1_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/interpret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Interpret Task
         * @description Turn a manager's free-text description into task fields for the chat to confirm.
         */
        post: operations["interpret_task_api_v1_tasks_interpret_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Task */
        patch: operations["update_task_api_v1_tasks__task_id__patch"];
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/match-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_tasks__task_id__match_runs_get"];
        put?: never;
        /**
         * Start Run
         * @description Queue a match run; poll GET /match-runs/{run_id} until it completes.
         */
        post: operations["start_run_api_v1_tasks__task_id__match_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Status
         * @description Mark filled, cancel (reason required) or reopen. Audited; nothing is ever automatic.
         */
        post: operations["change_status_api_v1_tasks__task_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminRunRead */
        AdminRunRead: {
            /** Candidate Count */
            candidate_count: number;
            /** Decision Set Version */
            decision_set_version: string;
            /** Error */
            error: string | null;
            /** Filter Reason Counts */
            filter_reason_counts: {
                [key: string]: number;
            };
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: string;
            /** Latency Ms */
            latency_ms: number;
            /** Model */
            model: string | null;
            /** Requested By Email */
            requested_by_email: string | null;
            /** Retrieved Count */
            retrieved_count: number;
            /** Run Flags */
            run_flags: string[];
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["RunStatus"];
            /** Task Code */
            task_code: string;
            /** Task Id */
            task_id: string;
            /** Task Title */
            task_title: string;
            thresholds?: components["schemas"]["ThresholdsRead"] | null;
            /** Thresholds Version */
            thresholds_version: string;
            /** Total Cost Usd */
            total_cost_usd: number;
        };
        /**
         * Band
         * @enum {string}
         */
        Band: "shortlist" | "review" | "hidden";
        /**
         * CandidateFeaturesRead
         * @description Facts computed by code (not AI) for one person and task.
         */
        CandidateFeaturesRead: {
            /** Available Capacity Pct */
            available_capacity_pct: number;
            /** Domain Project Count */
            domain_project_count: number;
            /** Inconsistent Data */
            inconsistent_data: boolean;
            /** Level Gap */
            level_gap: number;
            /** Low Data */
            low_data: boolean;
            /** Most Recent Relevant Skill Months */
            most_recent_relevant_skill_months: number | null;
            /** Must Have Coverage */
            must_have_coverage: number;
            /** Nice To Have Coverage */
            nice_to_have_coverage: number;
            /** Related Skill Hits */
            related_skill_hits: number;
            /** Years Gap */
            years_gap: number;
        };
        /**
         * CostBand
         * @enum {string}
         */
        CostBand: "A" | "B" | "C" | "D" | "E";
        /** DecisionOptionRead */
        DecisionOptionRead: {
            /** Description */
            description: string;
            /** Value */
            value: string;
        };
        /**
         * DecisionRead
         * @description A decision the engine asks about each candidate (read-only; defined in YAML).
         */
        DecisionRead: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Options */
            options: components["schemas"]["DecisionOptionRead"][];
            /** Question */
            question: string;
            /**
             * Type
             * @enum {string}
             */
            type: "bool" | "choice" | "score";
            /** Version */
            version: number;
        };
        /** DecisionResultRead */
        DecisionResultRead: {
            /** Chosen */
            chosen: string;
            /** Flags */
            flags: string[];
            /** Key */
            key: string;
            /** Probs */
            probs: {
                [key: string]: number;
            };
            /**
             * Type
             * @enum {string}
             */
            type: "bool" | "choice" | "score";
            /** Version */
            version: number;
        };
        /**
         * Domain
         * @enum {string}
         */
        Domain: "bfsi" | "healthcare" | "retail" | "manufacturing" | "public_sector" | "education" | "telecom" | "logistics";
        /** EmployeeRef */
        EmployeeRef: {
            /** Designation */
            designation: string;
            /** Employee Code */
            employee_code: string;
            /** Full Name */
            full_name: string;
            /** Id */
            id: string;
            level: components["schemas"]["Level"];
            location: components["schemas"]["Location"];
        };
        /** EvalReportRead */
        EvalReportRead: {
            /** Baseline Hit1 */
            baseline_hit1: number | null;
            /** Baseline Hit5 */
            baseline_hit5: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dataset Seed */
            dataset_seed: number;
            /** Decision Set Version */
            decision_set_version: string;
            /** Ece */
            ece: number | null;
            /** Id */
            id: string;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Model */
            model: string;
            /** Model Hit1 */
            model_hit1: number | null;
            /** Model Hit5 */
            model_hit5: number | null;
            /** Name */
            name: string;
            /** Retrieval Recall */
            retrieval_recall: number | null;
            /** Tasks */
            tasks: number | null;
        };
        /** EvalReportSummary */
        EvalReportSummary: {
            /** Baseline Hit1 */
            baseline_hit1: number | null;
            /** Baseline Hit5 */
            baseline_hit5: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dataset Seed */
            dataset_seed: number;
            /** Decision Set Version */
            decision_set_version: string;
            /** Ece */
            ece: number | null;
            /** Id */
            id: string;
            /** Model */
            model: string;
            /** Model Hit1 */
            model_hit1: number | null;
            /** Model Hit5 */
            model_hit5: number | null;
            /** Name */
            name: string;
            /** Retrieval Recall */
            retrieval_recall: number | null;
            /** Tasks */
            tasks: number | null;
        };
        /** ExcludedRead */
        ExcludedRead: {
            employee: components["schemas"]["EmployeeRef"];
            /** Filter Reasons */
            filter_reasons: string[];
        };
        /** ExplanationFactRead */
        ExplanationFactRead: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** ExplanationPointRead */
        ExplanationPointRead: {
            /** Fact Ids */
            fact_ids: string[];
            /** Text */
            text: string;
        };
        /**
         * ExplanationRead
         * @description Every point cites numbered facts; `facts` lists them so the UI can show the evidence.
         */
        ExplanationRead: {
            /** Facts */
            facts: components["schemas"]["ExplanationFactRead"][];
            /** Gaps */
            gaps: components["schemas"]["ExplanationPointRead"][];
            /** Strengths */
            strengths: components["schemas"]["ExplanationPointRead"][];
            /** Summary */
            summary: string;
        };
        /**
         * FeedbackAction
         * @enum {string}
         */
        FeedbackAction: "accept" | "reject";
        /** FeedbackInput */
        FeedbackInput: {
            action: components["schemas"]["FeedbackAction"];
            /** Comment */
            comment?: string | null;
            reject_reason?: components["schemas"]["RejectReason"] | null;
        };
        /** FeedbackRead */
        FeedbackRead: {
            action: components["schemas"]["FeedbackAction"];
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** By */
            by: string | null;
            /** Comment */
            comment: string | null;
            reject_reason: components["schemas"]["RejectReason"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InterpretRequest */
        InterpretRequest: {
            /** Known Clients */
            known_clients?: string[];
            /** Text */
            text: string;
        };
        /**
         * InterpretResponse
         * @description Fields understood from the message. Null = not stated; the chat asks for it.
         */
        InterpretResponse: {
            /** Allocation Pct Required */
            allocation_pct_required: number | null;
            /** Client Code */
            client_code: string | null;
            domain: components["schemas"]["Domain"] | null;
            /** Duration Weeks */
            duration_weeks: number | null;
            location: components["schemas"]["Location"] | null;
            /** Min Years Experience */
            min_years_experience: number | null;
            /** Model */
            model: string;
            /** Must Skills */
            must_skills: string[];
            /** Nice Skills */
            nice_skills: string[];
            /** Notes */
            notes: string[];
            priority: components["schemas"]["TaskPriority"] | null;
            required_level: components["schemas"]["Level"] | null;
            /** Start In Days */
            start_in_days: number | null;
            /** Title */
            title: string | null;
            /** Unmatched Skills */
            unmatched_skills: string[];
            work_mode: components["schemas"]["WorkMode"] | null;
        };
        /** LearningSummary */
        LearningSummary: {
            /** Accepted */
            accepted: number;
            /** Feedback Total */
            feedback_total: number;
            /** Holdout Examples */
            holdout_examples: number;
            /** Last Feedback At */
            last_feedback_at: string | null;
            /** Rejected By Reason */
            rejected_by_reason: {
                [key: string]: number;
            };
            /** Skipped */
            skipped: {
                [key: string]: number;
            };
            /** Training Examples */
            training_examples: number;
            /** Usable Examples */
            usable_examples: number;
        };
        /**
         * Level
         * @enum {string}
         */
        Level: "L1" | "L2" | "L3" | "L4" | "L5" | "L6";
        /**
         * Location
         * @enum {string}
         */
        Location: "hyderabad" | "bengaluru" | "pune" | "chennai" | "remote_india" | "usa" | "uk";
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MatchRunCreated */
        MatchRunCreated: {
            /** Run Id */
            run_id: string;
            status: components["schemas"]["RunStatus"];
        };
        /** MatchRunRead */
        MatchRunRead: {
            /** Candidate Count */
            candidate_count: number;
            /** Decision Set Version */
            decision_set_version: string;
            /** Error */
            error: string | null;
            /** Filter Reason Counts */
            filter_reason_counts: {
                [key: string]: number;
            };
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: string;
            /** Latency Ms */
            latency_ms: number;
            /** Model */
            model: string | null;
            /** Retrieved Count */
            retrieved_count: number;
            /** Run Flags */
            run_flags: string[];
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["RunStatus"];
            /** Task Id */
            task_id: string;
            thresholds?: components["schemas"]["ThresholdsRead"] | null;
            /** Thresholds Version */
            thresholds_version: string;
            /** Total Cost Usd */
            total_cost_usd: number;
        };
        /** Page[AdminRunRead] */
        Page_AdminRunRead_: {
            /** Items */
            items: components["schemas"]["AdminRunRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[DecisionRead] */
        Page_DecisionRead_: {
            /** Items */
            items: components["schemas"]["DecisionRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[EvalReportSummary] */
        Page_EvalReportSummary_: {
            /** Items */
            items: components["schemas"]["EvalReportSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[ExcludedRead] */
        Page_ExcludedRead_: {
            /** Items */
            items: components["schemas"]["ExcludedRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[MatchRunRead] */
        Page_MatchRunRead_: {
            /** Items */
            items: components["schemas"]["MatchRunRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[ShortlistItemRead] */
        Page_ShortlistItemRead_: {
            /** Items */
            items: components["schemas"]["ShortlistItemRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[SkillRead] */
        Page_SkillRead_: {
            /** Items */
            items: components["schemas"]["SkillRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[TaskRead] */
        Page_TaskRead_: {
            /** Items */
            items: components["schemas"]["TaskRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * RejectReason
         * @enum {string}
         */
        RejectReason: "skill_gap" | "level_mismatch" | "availability" | "domain_gap" | "client_preference" | "already_planned" | "other";
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "completed" | "failed";
        /** ShortlistItemRead */
        ShortlistItemRead: {
            band: components["schemas"]["Band"];
            /** Contradictions */
            contradictions: string[];
            /** Decisions */
            decisions: components["schemas"]["DecisionResultRead"][];
            employee: components["schemas"]["EmployeeRef"];
            explanation: components["schemas"]["ExplanationRead"] | null;
            /** Explanation Status */
            explanation_status: ("ok" | "unavailable") | null;
            features: components["schemas"]["CandidateFeaturesRead"];
            feedback: components["schemas"]["FeedbackRead"] | null;
            /** Flags */
            flags: string[];
            /** Id */
            id: string;
            /** Rank */
            rank: number;
            /** Rank Score */
            rank_score: number;
        };
        /**
         * SkillCategory
         * @enum {string}
         */
        SkillCategory: "language" | "framework" | "cloud" | "data" | "ai_ml" | "devops" | "testing" | "domain" | "soft";
        /** SkillRead */
        SkillRead: {
            /** Aliases */
            aliases: string[];
            category: components["schemas"]["SkillCategory"];
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** SkillRef */
        SkillRef: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** SkillRequirementCreate */
        SkillRequirementCreate: {
            /** Min Proficiency */
            min_proficiency: number;
            /** Must Have */
            must_have: boolean;
            /** Skill Id */
            skill_id: string;
        };
        /** SkillRequirementRead */
        SkillRequirementRead: {
            /** Min Proficiency */
            min_proficiency: number;
            /** Must Have */
            must_have: boolean;
            skill: components["schemas"]["SkillRef"];
        };
        /** TaskCreate */
        TaskCreate: {
            /** Allocation Pct Required */
            allocation_pct_required: number;
            /** Clearance Required */
            clearance_required?: string | null;
            /** Client Code */
            client_code: string;
            /** Client Timezone */
            client_timezone: string;
            /** Description */
            description: string;
            domain: components["schemas"]["Domain"];
            /** Duration Weeks */
            duration_weeks: number;
            /** Location Constraint */
            location_constraint: components["schemas"]["Location"][];
            max_cost_band: components["schemas"]["CostBand"];
            /** Min Timezone Overlap Hours */
            min_timezone_overlap_hours: number;
            /** Min Years Experience */
            min_years_experience: number;
            priority: components["schemas"]["TaskPriority"];
            required_level: components["schemas"]["Level"];
            /** Requirements */
            requirements: components["schemas"]["SkillRequirementCreate"][];
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** Title */
            title: string;
            work_mode: components["schemas"]["WorkMode"];
        };
        /**
         * TaskPriority
         * @enum {string}
         */
        TaskPriority: "low" | "medium" | "high" | "critical";
        /** TaskRead */
        TaskRead: {
            /** Allocation Pct Required */
            allocation_pct_required: number;
            /** Clearance Required */
            clearance_required: string | null;
            /** Client Code */
            client_code: string;
            /** Client Timezone */
            client_timezone: string;
            /** Code */
            code: string;
            /** Description */
            description: string;
            domain: components["schemas"]["Domain"];
            /** Duration Weeks */
            duration_weeks: number;
            /** Id */
            id: string;
            /** Location Constraint */
            location_constraint: components["schemas"]["Location"][];
            max_cost_band: components["schemas"]["CostBand"];
            /** Min Timezone Overlap Hours */
            min_timezone_overlap_hours: number;
            /** Min Years Experience */
            min_years_experience: number;
            priority: components["schemas"]["TaskPriority"];
            required_level: components["schemas"]["Level"];
            /** Requirements */
            requirements: components["schemas"]["SkillRequirementRead"][];
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            status: components["schemas"]["TaskStatus"];
            /** Title */
            title: string;
            work_mode: components["schemas"]["WorkMode"];
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "open" | "matching" | "shortlisted" | "filled" | "cancelled";
        /**
         * TaskStatusChange
         * @description A manager closes a task (filled / cancelled) or reopens it. Never automatic.
         */
        TaskStatusChange: {
            /** Note */
            note?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "filled" | "cancelled" | "open";
        };
        /**
         * TaskUpdate
         * @description Only the fields sent are changed. `requirements`, if sent, replaces the whole list.
         */
        TaskUpdate: {
            /** Allocation Pct Required */
            allocation_pct_required?: number | null;
            /** Clearance Required */
            clearance_required?: string | null;
            /** Client Code */
            client_code?: string | null;
            /** Client Timezone */
            client_timezone?: string | null;
            /** Description */
            description?: string | null;
            domain?: components["schemas"]["Domain"] | null;
            /** Duration Weeks */
            duration_weeks?: number | null;
            /** Location Constraint */
            location_constraint?: components["schemas"]["Location"][] | null;
            max_cost_band?: components["schemas"]["CostBand"] | null;
            /** Min Timezone Overlap Hours */
            min_timezone_overlap_hours?: number | null;
            /** Min Years Experience */
            min_years_experience?: number | null;
            priority?: components["schemas"]["TaskPriority"] | null;
            required_level?: components["schemas"]["Level"] | null;
            /** Requirements */
            requirements?: components["schemas"]["SkillRequirementCreate"][] | null;
            /** Start Date */
            start_date?: string | null;
            /** Title */
            title?: string | null;
            work_mode?: components["schemas"]["WorkMode"] | null;
        };
        /** ThresholdVersionRead */
        ThresholdVersionRead: {
            /** Active */
            active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: string | null;
            /** Label */
            label: string;
            /** Reason */
            reason: string;
            /** Review Min */
            review_min: number;
            /** Shortlist Min */
            shortlist_min: number;
            /** Version */
            version: number;
        };
        /** ThresholdsHistory */
        ThresholdsHistory: {
            active: components["schemas"]["ThresholdVersionRead"];
            /** Decision Key */
            decision_key: string;
            /** History */
            history: components["schemas"]["ThresholdVersionRead"][];
        };
        /** ThresholdsRead */
        ThresholdsRead: {
            /** Review Min */
            review_min: number;
            /** Shortlist Min */
            shortlist_min: number;
        };
        /** ThresholdsUpdate */
        ThresholdsUpdate: {
            /** Reason */
            reason: string;
            /** Review Min */
            review_min: number;
            /** Shortlist Min */
            shortlist_min: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /** UserRead */
        UserRead: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Id */
            id: string;
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "admin" | "resource_manager" | "viewer";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkMode
         * @enum {string}
         */
        WorkMode: "onsite" | "hybrid" | "remote";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    summary_api_v1_admin_learning_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningSummary"];
                };
            };
        };
    };
    export_api_v1_admin_learning_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                srtm_refresh?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_decisions_api_v1_decisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DecisionRead_"];
                };
            };
        };
    };
    get_thresholds_api_v1_decisions__key__thresholds_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThresholdsHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_thresholds_api_v1_decisions__key__thresholds_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThresholdsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThresholdsHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reports_api_v1_eval_reports_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_EvalReportSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_v1_eval_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalReportRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    all_runs_api_v1_match_runs_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["RunStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AdminRunRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_match_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    excluded_api_v1_match_runs__run_id__excluded_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ExcludedRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shortlist_api_v1_match_runs__run_id__shortlist_get: {
        parameters: {
            query?: {
                include_hidden?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ShortlistItemRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_feedback_api_v1_shortlist_items__item_id__feedback_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShortlistItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skills_api_v1_skills_get: {
        parameters: {
            query?: {
                category?: components["schemas"]["SkillCategory"] | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SkillRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_v1_tasks_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["TaskStatus"][] | null;
                priority?: components["schemas"]["TaskPriority"] | null;
                domain?: components["schemas"]["Domain"] | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TaskRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_v1_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interpret_task_api_v1_tasks_interpret_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterpretRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterpretResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_api_v1_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_tasks__task_id__match_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_MatchRunRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_v1_tasks__task_id__match_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRunCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_status_api_v1_tasks__task_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskStatusChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
